sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - "$HOME/.npm"
script:
  - NODE_ENV=production make
deploy:
  provider: pages
  local-dir: ./build/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
