sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - "$HOME/.npm"
script:
  - NODE_ENV=production make
addons:
  apt:
    update: true
    packages:
      - pcregrep
deploy:
  provider: pages
  local-dir: ./build/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
