sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - "$HOME/.npm"
install:
  - cd frontend && npm ci && cd ..
script:
  - cd frontend && THEME=cerulean npx webpack && cd ..
  - cd frontend && THEME=cosmo npx webpack && cd ..
  - cd frontend && THEME=cyborg npx webpack && cd ..
  - cd frontend && THEME=darkly npx webpack && cd ..
  - cd frontend && THEME=flatly npx webpack && cd ..
  - cd frontend && THEME=journal npx webpack && cd ..
  - cd frontend && THEME=litera npx webpack && cd ..
  - cd frontend && THEME=lumen npx webpack && cd ..
  - cd frontend && THEME=lux npx webpack && cd ..
  - cd frontend && THEME=materia npx webpack && cd ..
  - cd frontend && THEME=minty npx webpack && cd ..
  - cd frontend && THEME=pulse npx webpack && cd ..
  - cd frontend && THEME=sandstone npx webpack && cd ..
  - cd frontend && THEME=simplex npx webpack && cd ..
  - cd frontend && THEME=sketchy npx webpack && cd ..
  - cd frontend && THEME=slate npx webpack && cd ..
  - cd frontend && THEME=solar npx webpack && cd ..
  - cd frontend && THEME=spacelab npx webpack && cd ..
  - cd frontend && THEME=superhero npx webpack && cd ..
  - cd frontend && THEME=united npx webpack && cd ..
  - cd frontend && THEME=yeti npx webpack && cd ..
deploy:
  provider: pages
  local-dir: ./frontend/build/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
