sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - cd frontend
install:
  - npm ci
before_script:
  - cd frontend
script:
  - THEME=cerulean npx webpack
  - THEME=cosmo npx webpack
  - THEME=cyborg npx webpack
  - THEME=darkly npx webpack
  - THEME=flatly npx webpack
  - THEME=journal npx webpack
  - THEME=litera npx webpack
  - THEME=lumen npx webpack
  - THEME=lux npx webpack
  - THEME=materia npx webpack
  - THEME=minty npx webpack
  - THEME=pulse npx webpack
  - THEME=sandstone npx webpack
  - THEME=simplex npx webpack
  - THEME=sketchy npx webpack
  - THEME=slate npx webpack
  - THEME=solar npx webpack
  - THEME=spacelab npx webpack
  - THEME=superhero npx webpack
  - THEME=united npx webpack
  - THEME=yeti npx webpack
deploy:
  provider: pages
  local-dir: ./frontend/build/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
