sudo: false
language: node_js
node_js: 10
cache:
  directories:
    - "$HOME/.npm"
script:
  - npx webpack --theme=cerulean --mode=production
  - npx webpack --theme=cosmo --mode=production
  - npx webpack --theme=cyborg --mode=production
  - npx webpack --theme=darkly --mode=production
  - npx webpack --theme=flatly --mode=production
  - npx webpack --theme=journal --mode=production
  - npx webpack --theme=litera --mode=production
  - npx webpack --theme=lumen --mode=production
  - npx webpack --theme=lux --mode=production
  - npx webpack --theme=materia --mode=production
  - npx webpack --theme=minty --mode=production
  - npx webpack --theme=pulse --mode=production
  - npx webpack --theme=sandstone --mode=production
  - npx webpack --theme=simplex --mode=production
  - npx webpack --theme=sketchy --mode=production
  - npx webpack --theme=slate --mode=production
  - npx webpack --theme=solar --mode=production
  - npx webpack --theme=spacelab --mode=production
  - npx webpack --theme=superhero --mode=production
  - npx webpack --theme=united --mode=production
  - npx webpack --theme=yeti --mode=production
deploy:
  provider: pages
  local-dir: ./docs/
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
